#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
本地假接口：把 LLM 和语音识别这两条"要联网"的路在离线环境下也能测通。

它同时假装两个端点（都是 OpenAI 兼容形状）：
  POST /v1/chat/completions          返回一份编好的动效文案 JSON
  POST /v1/audio/transcriptions      返回一段假的分段转写（verbose_json）

用法：
  python agent/_mock_api.py 8788
  set MK_LLM_BASE=http://127.0.0.1:8788
  set MK_LLM_KEY=test
  set MK_ASR_BASE=http://127.0.0.1:8788
  set MK_ASR_KEY=test
  python agent/autopilot.py --video in.mp4 --out projects/demo

它只是开发/自检用的，正式跑请把 baseUrl 换成真接口。
"""

import json
import sys
from http.server import BaseHTTPRequestHandler, HTTPServer

CANNED_CREATIVE = {
    "style": "slopcore",
    "title": "MOCK RUN",
    "kicker": "OFFLINE SELF-TEST",
    "note": "no network required",
    "hooks": ["MOCK", "SIGNAL", "LOCKED", "TRACE", "RECORD", "EXIT", "AGAIN", "END"],
    "tickers": {
        "top": "MOCK RUN   MOTIONKIT AGENT   OFFLINE SELF TEST",
        "bottom": "NO API KEY   NO PROBLEM   PIPELINE VERIFIED",
    },
    "terminal": [
        "> mock llm endpoint",
        "> creative brief injected",
        "> scene generated by director",
        "> render path untouched",
        "> status: OK",
    ],
    "chapters": ["01", "02", "03"],
}

FAKE_SEGMENTS = [
    {"start": 0.4, "end": 2.6, "text": "这是一段假的语音识别结果"},
    {"start": 3.2, "end": 6.1, "text": "用来验证字幕链路能不能跑通"},
    {"start": 7.0, "end": 10.5, "text": "mock transcription works end to end"},
]


class Handler(BaseHTTPRequestHandler):
    def log_message(self, *a):
        pass

    def _json(self, obj, code=200):
        body = json.dumps(obj, ensure_ascii=False).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self):
        n = int(self.headers.get("Content-Length") or 0)
        raw = self.rfile.read(n) if n else b""
        path = self.path.split("?")[0]
        if path.endswith("/chat/completions"):
            self._json({"choices": [{"message": {"role": "assistant",
                                                 "content": json.dumps(CANNED_CREATIVE, ensure_ascii=False)}}]})
            return
        if path.endswith("/audio/transcriptions"):
            # 真的走了一遍 multipart 上传，这里只检查它确实带了文件内容
            ok = b"RIFF" in raw or b"ID3" in raw or len(raw) > 2000
            if not ok:
                self._json({"error": "没收到音频数据"}, 400)
                return
            self._json({"task": "transcribe", "language": "zh",
                        "duration": 10.5, "text": " ".join(s["text"] for s in FAKE_SEGMENTS),
                        "segments": FAKE_SEGMENTS})
            return
        self._json({"error": "not found: " + path}, 404)

    def do_GET(self):
        self._json({"ok": True, "endpoints": ["/v1/chat/completions", "/v1/audio/transcriptions"]})


if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8788
    print("mock api on http://127.0.0.1:%d" % port, flush=True)
    HTTPServer(("127.0.0.1", port), Handler).serve_forever()
